networks:
  - 127.0.0.1/8
  - 204.232.175.64/27
  - 192.30.252.0/22

ssh_key: ~/.ssh/identity

workdir: /dev/shm

repo_url: git@github.com:ontohub/ontohub.git
push_dummy: /dev/shm/push_dummy.git

#log_requests: true

merge:
  staging: develop
  staging: staging.ontohub.org
  develop: develop.ontohub.org

deploy:
  staging.ontohub.org:
    after_change_to: staging
    host: staging.ontohub.org
  develop.ontohub.org:
    after_change_to: develop
    host: develop.ontohub.org
